# Generated by Django 3.0.2 on 2020-01-17 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_single_lang', models.BooleanField(blank=True, default=False)),
                ('is_visible', models.BooleanField(blank=True, default=True)),
                ('html_list', models.TextField(blank=True, null=True)),
                ('html_item', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content',
                'default_related_name': 'contents',
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('file_url', models.FileField(blank=True, upload_to='content/items/file_url')),
                ('url', models.CharField(blank=True, max_length=250)),
                ('order_index', models.PositiveIntegerField(blank=True, default=0)),
                ('is_single_lang', models.BooleanField(blank=True, default=False)),
                ('is_visible', models.BooleanField(blank=True, default=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_items', to='web_lib_core.Content')),
            ],
            options={
                'db_table': 'content_item',
                'ordering': ('order_index',),
                'default_related_name': 'content_items',
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('file_is_image', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'content_type',
                'ordering': ('order_index',),
                'default_related_name': 'content_types',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'language',
                'default_related_name': 'languages',
            },
        ),
        migrations.CreateModel(
            name='TranslationPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name="Ім'я сторінки")),
                ('code', models.CharField(default='', max_length=200, unique=True, verbose_name='Код')),
                ('template_name', models.CharField(default='', max_length=200, verbose_name='Назва файлу')),
            ],
            options={
                'db_table': 'translation_page',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TranslationText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_code', models.CharField(help_text='Коротке значення', max_length=250, unique=True, verbose_name='Ідентифікатор тексту')),
                ('EN', models.TextField(blank=True, default='', verbose_name='Англійською')),
                ('RU', models.TextField(blank=True, default='', verbose_name='Російською')),
                ('UA', models.TextField(blank=True, default='', verbose_name='Українською')),
                ('DE', models.TextField(blank=True, default='', verbose_name='Німецькою')),
            ],
            options={
                'db_table': 'translation_text',
            },
        ),
        migrations.CreateModel(
            name='TranslationPageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_texts', to='web_lib_core.TranslationPage', verbose_name='Сторінка')),
                ('texts', models.ManyToManyField(related_name='page_texts', to='web_lib_core.TranslationText', verbose_name="Слова, прив'язані до сторінки")),
            ],
            options={
                'db_table': 'translation_page_text',
                'default_related_name': 'page_texts',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.CharField(blank=True, max_length=250)),
                ('root_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='web_lib_core.Content')),
            ],
            options={
                'db_table': 'page',
                'default_related_name': 'pages',
            },
        ),
        migrations.CreateModel(
            name='ContentLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(blank=True, default=True)),
                ('html_list', models.TextField(blank=True, null=True)),
                ('html_item', models.TextField(blank=True, null=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_langs', to='web_lib_core.Content')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_langs', to='web_lib_core.Language')),
            ],
            options={
                'db_table': 'content_lang',
                'default_related_name': 'content_langs',
            },
        ),
        migrations.CreateModel(
            name='ContentItemLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(blank=True, upload_to='content/items/lang/file_url')),
                ('url', models.CharField(blank=True, max_length=250)),
                ('html', models.TextField(blank=True)),
                ('content_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_item_langs', to='web_lib_core.ContentItem')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_item_langs', to='web_lib_core.Language')),
            ],
            options={
                'db_table': 'content_item_lang',
                'default_related_name': 'content_item_langs',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='web_lib_core.ContentType'),
        ),
    ]
