# Generated by Django 3.0.2 on 2020-02-13 10:04

from django.db import migrations
import nodeads_libs.web_lib_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0002_auto_20200212_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='html_item',
            field=nodeads_libs.web_lib_core.models.NonStrippingCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentlang',
            name='html_item',
            field=nodeads_libs.web_lib_core.models.NonStrippingCharField(blank=True, null=True),
        ),
    ]
