# Generated by Django 3.0.2 on 2020-02-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0003_auto_20200213_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
