# Generated by Django 3.0.2 on 2020-02-19 09:23

from django.db import migrations, models
import nodeads_libs.web_lib_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0012_auto_20200219_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimagegroup',
            name='preview_url',
            field=models.ImageField(blank=True, null=True, upload_to='content/items/upload_images'),
        ),
    ]
