# Generated by Django 3.0.2 on 2020-02-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0014_auto_20200219_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimagegroup',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dimagegrouplang',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dmusicgroup',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dmusicgrouplang',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dvideogroup',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dvideogrouplang',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
