# Generated by Django 3.0.2 on 2020-02-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0015_auto_20200219_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_reg_exp',
            field=models.BooleanField(default=False),
        ),
    ]
