# Generated by Django 3.0.2 on 2020-02-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0016_page_is_reg_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('value', models.CharField(blank=True, max_length=120, null=True)),
                ('is_reg_exp', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page_params', to='web_lib_core.Page')),
            ],
            options={
                'db_table': 'page_param',
                'default_related_name': 'page_params',
            },
        ),
    ]
