# Generated by Django 3.0.2 on 2020-02-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0017_pageparam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitemlang',
            name='html',
        ),
        migrations.AddField(
            model_name='contentitemlang',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
