# Generated by Django 3.0.2 on 2020-02-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0018_auto_20200226_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='inner_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitemlang',
            name='inner_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
