# Generated by Django 3.0.2 on 2020-03-04 10:12

from django.db import migrations, models
import django.db.models.deletion
import nodeads_libs.web_lib_core.models
import nodeads_libs.web_lib_core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0019_auto_20200226_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(blank=True, upload_to=nodeads_libs.web_lib_core.models.type_based_upload_to, validators=[nodeads_libs.web_lib_core.validators.validate_size])),
                ('preview_url', models.FileField(blank=True, upload_to=nodeads_libs.web_lib_core.models.type_based_upload_to, validators=[nodeads_libs.web_lib_core.validators.validate_size])),
                ('is_visible', models.BooleanField(blank=True, default=False)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'd_post',
                'default_related_name': 'd_posts',
            },
        ),
        migrations.CreateModel(
            name='DPostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'd_post_group',
                'default_related_name': 'd_post_groups',
            },
        ),
        migrations.CreateModel(
            name='DPostLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=1024, null=True)),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d_post_langs', to='web_lib_core.Language')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='d_post_langs', to='web_lib_core.DPost')),
            ],
            options={
                'db_table': 'd_post_lang',
                'default_related_name': 'd_post_langs',
            },
        ),
        migrations.CreateModel(
            name='DPostGroupLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d_post_group_langs', to='web_lib_core.Language')),
                ('post_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='d_post_group_langs', to='web_lib_core.DPostGroup')),
            ],
            options={
                'db_table': 'd_post_group_lang',
                'default_related_name': 'd_post_group_langs',
            },
        ),
        migrations.AddField(
            model_name='dpost',
            name='post_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='d_posts', to='web_lib_core.DPostGroup'),
        ),
    ]
