# Generated by Django 3.0.2 on 2020-03-05 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0020_auto_20200304_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('post_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='d_post_tags', to='web_lib_core.DPostGroup')),
            ],
            options={
                'db_table': 'd_post_tag',
                'default_related_name': 'd_post_tags',
            },
        ),
        migrations.RemoveField(
            model_name='dpost',
            name='post_group',
        ),
        migrations.CreateModel(
            name='DPostTagLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='d_post_tag_links', to='web_lib_core.DPost')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='d_post_tag_links', to='web_lib_core.DPostTag')),
            ],
            options={
                'db_table': 'd_post_tag_link',
                'default_related_name': 'd_post_tag_links',
            },
        ),
    ]
