# Generated by Django 3.0.2 on 2020-03-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0021_auto_20200305_1504'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentitemlang',
            unique_together={('content_item', 'lang')},
        ),
    ]
