# Generated by Django 3.0.2 on 2020-03-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0023_auto_20200311_1811'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentitemlang',
            unique_together={('content_item', 'lang')},
        ),
    ]
