# Generated by Django 3.0.2 on 2020-03-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0024_auto_20200323_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
                ('keywords', models.CharField(blank=True, max_length=4096, null=True)),
                ('pagetitle', models.CharField(max_length=4096)),
                ('imageid', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('titleen', models.CharField(blank=True, max_length=512, null=True)),
                ('fulltext', models.TextField(blank=True, null=True)),
                ('fulltexten', models.TextField(blank=True, null=True)),
                ('previewtext', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('authorid', models.IntegerField(blank=True, null=True)),
                ('lastmodifier', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.IntegerField()),
                ('charity', models.SmallIntegerField()),
                ('youtube', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
    ]
