# Generated by Django 3.0.2 on 2020-03-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0025_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpostlang',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dpostlang',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dposttag',
            name='old_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
