# Generated by Django 3.0.2 on 2020-03-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0026_auto_20200323_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTagLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.IntegerField(blank=True, null=True)),
                ('postid', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_tag_link',
                'managed': False,
            },
        ),
    ]
