# Generated by Django 3.0.2 on 2020-03-23 19:54

from django.db import migrations, models
import nodeads_libs.web_lib_core.models
import nodeads_libs.web_lib_core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0027_posttaglink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimage',
            name='preview_url',
            field=models.FileField(blank=True, max_length=1024, upload_to=nodeads_libs.web_lib_core.models.type_based_upload_to, validators=[nodeads_libs.web_lib_core.validators.validate_size]),
        ),
        migrations.AlterField(
            model_name='dimage',
            name='url',
            field=models.FileField(blank=True, max_length=1024, upload_to=nodeads_libs.web_lib_core.models.type_based_upload_to, validators=[nodeads_libs.web_lib_core.validators.validate_size]),
        ),
        migrations.AlterField(
            model_name='dmusic',
            name='preview_url',
            field=models.FileField(blank=True, max_length=1024, upload_to=nodeads_libs.web_lib_core.models.type_based_upload_to, validators=[nodeads_libs.web_lib_core.validators.validate_size]),
        ),
        migrations.AlterField(
            model_name='dmusic',
            name='url',
            field=models.FileField(blank=True, max_length=1024, upload_to=nodeads_libs.web_lib_core.models.type_based_upload_to, validators=[nodeads_libs.web_lib_core.validators.validate_size]),
        ),
        migrations.AlterField(
            model_name='dpost',
            name='preview_url',
            field=models.FileField(blank=True, max_length=1024, upload_to=nodeads_libs.web_lib_core.models.type_based_upload_to, validators=[nodeads_libs.web_lib_core.validators.validate_size]),
        ),
        migrations.AlterField(
            model_name='dpost',
            name='url',
            field=models.FileField(blank=True, max_length=1024, upload_to=nodeads_libs.web_lib_core.models.type_based_upload_to, validators=[nodeads_libs.web_lib_core.validators.validate_size]),
        ),
        migrations.AlterField(
            model_name='dvideo',
            name='preview_url',
            field=models.FileField(blank=True, max_length=1024, upload_to=nodeads_libs.web_lib_core.models.type_based_upload_to, validators=[nodeads_libs.web_lib_core.validators.validate_size]),
        ),
        migrations.AlterField(
            model_name='dvideo',
            name='url',
            field=models.FileField(blank=True, max_length=1024, upload_to=nodeads_libs.web_lib_core.models.type_based_upload_to, validators=[nodeads_libs.web_lib_core.validators.validate_size]),
        ),
    ]
