# Generated by Django 3.0.2 on 2020-03-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0024_auto_20200311_1812'),
        ('web_lib_core', '0029_auto_20200323_2204'),
    ]

    operations = [
    ]
