# Generated by Django 3.0.2 on 2020-03-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0033_auto_20200325_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dpost',
            name='full_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dpost',
            name='name',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
