# Generated by Django 3.0.2 on 2020-03-26 12:23

from django.db import migrations, models
import django.db.models.deletion
import nodeads_libs.web_lib_core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0035_auto_20200326_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPostVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_code', models.CharField(max_length=64)),
                ('is_visible', models.BooleanField(blank=True, default=True)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='d_post_videos', to='web_lib_core.DPost')),
            ],
            options={
                'db_table': 'd_post_video',
                'default_related_name': 'd_post_videos',
            },
        ),
        migrations.CreateModel(
            name='DPostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/items/post_images', validators=[nodeads_libs.web_lib_core.validators.validate_size])),
                ('is_visible', models.BooleanField(blank=True, default=True)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='d_post_images', to='web_lib_core.DPost')),
            ],
            options={
                'db_table': 'd_post_image',
                'default_related_name': 'd_post_images',
            },
        ),
    ]
