# Generated by Django 3.0.2 on 2020-03-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0036_dpostimage_dpostvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVideoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoid', models.IntegerField(blank=True, null=True)),
                ('postid', models.IntegerField(blank=True, null=True)),
                ('youtubecode', models.CharField(max_length=64)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('small', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_video_link',
                'managed': False,
            },
        ),
    ]
