# Generated by Django 3.0.2 on 2020-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0037_postvideolink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverid', models.IntegerField(blank=True, null=True)),
                ('dir', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('typeid', models.IntegerField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=32, null=True)),
                ('src', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('alt', models.CharField(blank=True, max_length=512, null=True)),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('authorid', models.IntegerField(blank=True, null=True)),
                ('lastmodifier', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageid', models.IntegerField(blank=True, null=True)),
                ('postid', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_image_link',
                'managed': False,
            },
        ),
    ]
