# Generated by Django 3.0.2 on 2020-03-30 14:00

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0038_images_postimagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpostimage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '40x40', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
