# Generated by Django 3.0.2 on 2020-04-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0039_dpostimage_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitemlang',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
