# Generated by Django 3.0.2 on 2020-04-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0043_auto_20200407_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTagGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'video_tag_groups',
                'managed': False,
            },
        ),
    ]
