# Generated by Django 3.0.2 on 2020-04-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0044_videotaggroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='DVideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('video_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='d_video_tags', to='web_lib_core.DVideoGroup')),
            ],
            options={
                'db_table': 'd_video_tag',
                'default_related_name': 'd_video_tags',
            },
        ),
        migrations.CreateModel(
            name='DVideoTagLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='d_video_tag_links', to='web_lib_core.DVideoTag')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='d_video_tag_links', to='web_lib_core.DVideo')),
            ],
            options={
                'db_table': 'd_video_tag_link',
                'default_related_name': 'd_video_tag_links',
            },
        ),
    ]
