# Generated by Django 3.0.2 on 2020-04-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0047_dvideo_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceid', models.IntegerField(blank=True, null=True)),
                ('serverid', models.CharField(blank=True, max_length=32, null=True)),
                ('serveriden', models.CharField(blank=True, max_length=32, null=True)),
                ('imageid', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('titleen', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('authorid', models.IntegerField(blank=True, null=True)),
                ('lastmodifier', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'videos',
                'managed': False,
            },
        ),
    ]
