# Generated by Django 3.0.2 on 2020-04-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0048_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvideo',
            name='video_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d_videos', to='web_lib_core.DVideoGroup'),
        ),
    ]
