# Generated by Django 3.0.2 on 2020-04-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lib_core', '0049_auto_20200408_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimage',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dmusic',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dpost',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dvideo',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
